#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
#Tue Jul 28 15:55:40 QYZT 2026
boolean.villages.enabled_custom_config=true
int.villages.salt=10387312
int.villages.separation=20
int.villages.spacing=45
