#Scream&Disappear Death Sounds Configurations
[common]
	tyler1 = true
	emoji = true
	yoda = true
	vsause_michael = true
	moist_cr1tikalz = true
	tom_scott = true
	popaye_bisquit_guy = true
	nikocado_avocado = true
	tommyinnit = true
